import type {
  BlogPost,
  CareerOpening,
  ContactInquiry,
  DriverApplication,
  InternalMember,
  JobApplication,
  Partner,
  TeamMember,
  Testimonial,
} from "./types";

export const TEAM: TeamMember[] = [
  {
    id: "t1",
    name: "Rajesh Mehta",
    role: "Chief Executive Officer",
    department: "Executive",
    email: "rajesh.mehta@bikewo.com",
    joinedAt: "2019-03-15",
    status: "active",
  },
  {
    id: "t2",
    name: "Priya Sharma",
    role: "Chief Operating Officer",
    department: "Operations",
    email: "priya.sharma@bikewo.com",
    joinedAt: "2020-01-08",
    status: "active",
  },
  {
    id: "t3",
    name: "Arun Patel",
    role: "Head of Energy Infrastructure",
    department: "Energy",
    email: "arun.patel@bikewo.com",
    joinedAt: "2021-06-22",
    status: "active",
  },
  {
    id: "t4",
    name: "Sneha Reddy",
    role: "VP, Shram Sainik",
    department: "Mobility",
    email: "sneha.reddy@bikewo.com",
    joinedAt: "2022-02-14",
    status: "active",
  },
  {
    id: "t5",
    name: "Vikram Singh",
    role: "Chief Technology Officer",
    department: "Technology",
    email: "vikram.singh@bikewo.com",
    joinedAt: "2020-09-01",
    status: "inactive",
  },
];

export const BLOGS: BlogPost[] = [
  {
    id: "b1",
    title: "Charge hub network crosses its next corridor milestone",
    slug: "charge-hub-corridor-milestone",
    category: "Energy Infrastructure",
    author: "Communications Team",
    excerpt:
      "The highway corridor build-out adds fast-charging capacity between three states.",
    publishedAt: "2026-07-22",
    status: "published",
  },
  {
    id: "b2",
    title: "Training academy expands to five new cities",
    slug: "training-academy-expansion",
    category: "Shram Sainik",
    author: "HR Team",
    excerpt:
      "Road safety, battery handling and customer service, delivered in regional languages.",
    publishedAt: "2026-06-30",
    status: "published",
  },
  {
    id: "b3",
    title: "Predictive maintenance moves from pilot to fleet-wide",
    slug: "predictive-maintenance-fleet-wide",
    category: "BikeWo VZN",
    author: "Product Team",
    excerpt:
      "Telemetry now flags battery degradation before it becomes an unplanned workshop visit.",
    publishedAt: "2026-06-11",
    status: "published",
  },
  {
    id: "b4",
    title: "Q3 sustainability report highlights",
    slug: "q3-sustainability-report",
    category: "Sustainability",
    author: "ESG Team",
    excerpt: "Annual emissions avoided and second-life battery pathways in review.",
    publishedAt: null,
    status: "draft",
  },
];

export const CAREERS: CareerOpening[] = [
  {
    id: "c1",
    title: "Charging Network Engineer",
    location: "Pune",
    type: "Full-time",
    department: "Energy Infrastructure",
    postedAt: "2026-08-01",
    applications: 24,
    status: "open",
  },
  {
    id: "c2",
    title: "Fleet Data Scientist — VZN",
    location: "Bengaluru",
    type: "Full-time",
    department: "Technology",
    postedAt: "2026-07-28",
    applications: 18,
    status: "open",
  },
  {
    id: "c3",
    title: "Regional Service Manager",
    location: "Lucknow",
    type: "Full-time",
    department: "Lifecycle Services",
    postedAt: "2026-07-15",
    applications: 31,
    status: "open",
  },
  {
    id: "c4",
    title: "Channel Development Lead",
    location: "Ahmedabad",
    type: "Full-time",
    department: "Mobility Distribution",
    postedAt: "2026-06-20",
    applications: 12,
    status: "closed",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "s1",
    quote:
      "We moved 60 vehicles onto lease and the cost per kilometre finally became something I could forecast.",
    name: "Fleet operator, Pune",
    role: "Fleet operator",
    status: "published",
    sortOrder: 1,
  },
  {
    id: "s2",
    quote:
      "Service used to be the reason customers hesitated. Now Enlite handles it and the conversation is about range, not repairs.",
    name: "Dealer principal, Jaipur",
    role: "Dealer principal",
    status: "published",
    sortOrder: 2,
  },
  {
    id: "s3",
    quote:
      "Zero joining fee meant I could start the same week. The weekly payout is what keeps my household running.",
    name: "Driver-partner, Lucknow",
    role: "Driver-partner",
    status: "published",
    sortOrder: 3,
  },
];

export const PARTNERS: Partner[] = [
  { id: "p1", name: "Positiev Mobility", website: "https://positiev.in", sortOrder: 1, status: "published" },
  { id: "p2", name: "Enlite EV Care", website: "https://enlite.in", sortOrder: 2, status: "published" },
  { id: "p3", name: "Tata Power EV", website: "https://tatapower.com", sortOrder: 3, status: "published" },
  { id: "p4", name: "Ather Energy", website: "https://atherenergy.com", sortOrder: 4, status: "published" },
  { id: "p5", name: "Partner 5", website: "", sortOrder: 5, status: "draft" },
];

export const CONTACT_INQUIRIES: ContactInquiry[] = [
  {
    id: "ci1",
    name: "Amit Khanna",
    email: "amit.khanna@fleetco.in",
    phone: "+91 98765 43210",
    company: "FleetCo Logistics",
    topic: "Fleet Leasing",
    message: "Interested in leasing 50 three-wheelers for our Pune operations.",
    submittedAt: "2026-08-28T10:30:00",
    status: "new",
  },
  {
    id: "ci2",
    name: "Deepa Nair",
    email: "deepa@greencharge.org",
    phone: "+91 91234 56789",
    company: "GreenCharge Foundation",
    topic: "Charging Infrastructure",
    message: "Looking to partner on highway corridor charging hubs in Kerala.",
    submittedAt: "2026-08-27T14:15:00",
    status: "in_progress",
  },
  {
    id: "ci3",
    name: "Rohit Verma",
    email: "rohit.verma@gmail.com",
    phone: "+91 99887 76655",
    company: "",
    topic: "General Inquiry",
    message: "Would like to know about dealer opportunities in Bhopal.",
    submittedAt: "2026-08-26T09:00:00",
    status: "resolved",
  },
  {
    id: "ci4",
    name: "Kavita Joshi",
    email: "kavita.j@investcorp.com",
    phone: "+91 97654 32109",
    company: "InvestCorp",
    topic: "Investor Relations",
    message: "Request for latest quarterly presentation and ESG report.",
    submittedAt: "2026-08-25T16:45:00",
    status: "new",
  },
];

export const DRIVER_APPLICATIONS: DriverApplication[] = [
  {
    id: "da1",
    name: "Suresh Yadav",
    phone: "+91 98123 45678",
    city: "Lucknow",
    vehicleType: "Electric 3W",
    experience: "2 years",
    submittedAt: "2026-08-28T08:20:00",
    status: "pending",
  },
  {
    id: "da2",
    name: "Mohammed Rafiq",
    phone: "+91 97012 34567",
    city: "Hyderabad",
    vehicleType: "Electric 2W",
    experience: "6 months",
    submittedAt: "2026-08-27T11:30:00",
    status: "reviewing",
  },
  {
    id: "da3",
    name: "Lakshmi Devi",
    phone: "+91 95678 90123",
    city: "Chennai",
    vehicleType: "Electric 3W",
    experience: "3 years",
    submittedAt: "2026-08-26T15:00:00",
    status: "accepted",
  },
  {
    id: "da4",
    name: "Harpreet Singh",
    phone: "+91 98760 12345",
    city: "Amritsar",
    vehicleType: "Electric 2W",
    experience: "1 year",
    submittedAt: "2026-08-24T10:10:00",
    status: "rejected",
  },
];

export const JOB_APPLICATIONS: JobApplication[] = [
  {
    id: "ja1",
    name: "Ananya Iyer",
    email: "ananya.iyer@email.com",
    position: "Charging Network Engineer",
    submittedAt: "2026-08-28T12:00:00",
    status: "pending",
  },
  {
    id: "ja2",
    name: "Rahul Desai",
    email: "rahul.desai@email.com",
    position: "Fleet Data Scientist — VZN",
    submittedAt: "2026-08-27T09:30:00",
    status: "reviewing",
  },
  {
    id: "ja3",
    name: "Meera Kapoor",
    email: "meera.kapoor@email.com",
    position: "Regional Service Manager",
    submittedAt: "2026-08-25T17:45:00",
    status: "pending",
  },
];

export const INTERNAL_MEMBERS: InternalMember[] = [
  {
    id: "im1",
    name: "Admin User",
    email: "admin@bikewo.com",
    cmsRole: "super_admin",
    department: "Technology",
    invitedAt: "2025-01-10",
    lastActiveAt: "2026-08-29T10:30:00",
    status: "active",
  },
  {
    id: "im2",
    name: "Priya Sharma",
    email: "priya.sharma@bikewo.com",
    cmsRole: "admin",
    department: "Operations",
    invitedAt: "2025-03-15",
    lastActiveAt: "2026-08-28T16:45:00",
    status: "active",
  },
  {
    id: "im3",
    name: "Communications Team",
    email: "comms@bikewo.com",
    cmsRole: "editor",
    department: "Marketing",
    invitedAt: "2025-06-01",
    lastActiveAt: "2026-08-27T11:20:00",
    status: "active",
  },
  {
    id: "im4",
    name: "HR Team",
    email: "hr@bikewo.com",
    cmsRole: "reviewer",
    department: "Human Resources",
    invitedAt: "2025-08-20",
    lastActiveAt: "2026-08-26T09:15:00",
    status: "active",
  },
  {
    id: "im5",
    name: "Investor Relations",
    email: "ir@bikewo.com",
    cmsRole: "viewer",
    department: "Finance",
    invitedAt: "2026-02-01",
    lastActiveAt: "2026-08-20T14:00:00",
    status: "active",
  },
  {
    id: "im6",
    name: "New Hire",
    email: "new.hire@bikewo.com",
    cmsRole: "editor",
    department: "Marketing",
    invitedAt: "2026-08-28",
    lastActiveAt: null,
    status: "invited",
  },
];
